### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by yienzhu** [eycorsican/Mellow#1]
macOS 10.14.5 (18F132)

错误信息
Uncaught Exception:
ReferenceError: mainWindow is not defined
    at App.<anonymous> (/Applications/Mellow.app/Contents/Resources/app.asar/main.js:247:3)
    at App.emit (events.js:194:13)

**Comment by eycorsican** [comment]
这些错误可以忽略不管，在菜单栏图标那里操作就行

**Comment by yienzhu** [comment]
菜单栏没有出现图标

**Comment by eycorsican** [comment]
我不信🤨

**Comment by yienzhu** [comment]
哈哈😂不信也没办法的，确实是没出现。

**Comment by hexd2019** [comment]
状态栏点击start，出现js相关错误，我也不懂，图标一直灰度色，估计打开时应该是红色吧

**Comment by hexd2019** [comment]
点击安装helper也没有反应

**Comment by hexd2019** [comment]
感谢你的这个软件，希望完善后能用，clashx不好用

**Comment by hexd2019** [comment]
没有出现js的问题，出现图标后安装helper，然后start，运行找不到cfg.json错误,个人判断helper没有安装成功，于是下载zip文件，把里面package.json改了cfg.json,放进该路径的文件夹，运行start，没有显示出错，但图标灰色，也没有运行。估计还是安装helper的问题。谢谢你的更新。

**Comment by hexd2019** [comment]
Failed to start the Core, try reinstalling the helper, and see "~/Library/Logs/Mellow/log.log" for more details.

**Comment by hexd2019** [comment]
Error: Cannot find module '/Applications/Mellow.app/Contents/Frameworks/Mellow Helper.app/Contents/Resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11

**Comment by eycorsican** [comment]
最新 release 应该没这些提示了吧？我关了
