### ISSUE TITLE
Failed to start the core

### ISSUE THREAD

**Issue by thiefor** [eycorsican/Mellow#10]
[log.txt](https://github.com/eycorsican/Mellow/files/3540242/log.txt)

**Comment by eycorsican** [comment]
v0.0.10 应该已修复：https://github.com/eycorsican/Mellow/releases/tag/v0.0.10

**Comment by Jephen** [comment]
我也遇到了这个提示
[log.log](https://github.com/eycorsican/Mellow/files/3586134/log.log)

**Comment by eycorsican** [comment]
更新
