### ISSUE TITLE
什么时候出一版Linux的呢？

### ISSUE THREAD

**Issue by PterX** [eycorsican/Mellow#2]

**Comment by BingLingGroup** [comment]
linux不是有proxychain吗

**Comment by PterX** [comment]
> linux不是有proxychain吗

你看下大佬的工具就知道了，这个工具会比proxychain更好用

**Comment by eycorsican** [comment]
支持 Linux 应该也很简单，但我不知道比如在 Ubuntu 上写好 electron UI 后能不能在其它的发行版上正常打开，不熟悉各种
Linux 的界面系统...

**Comment by PterX** [comment]
> 支持 Linux 应该也很简单，但我不知道比如在 Ubuntu 上写好 electron UI 后能不能在其它的发行版上正常打开，不熟悉各种 Linux 的界面系统...

electron 本身兼容性还是可以的，之前用过一些electron开发的工具，都还不错

**Comment by eycorsican** [comment]
https://github.com/eycorsican/Mellow/releases/download/v0.0.13/Mellow-0.0.13.AppImage
