### ISSUE TITLE
指定进程的时候是否可以指定父进程

### ISSUE THREAD

**Issue by patrickwangqy** [eycorsican/mellow#22]
指定进程的时候是否可以指定父进程，然后下面所有的子进程都按父进程的配置来

**Comment by eycorsican** [comment]
具体使用场景是？

**Comment by patrickwangqy** [comment]
看win10的任务管理器里面一个程序下面会有很多的进程，一般想让这个软件走或者不走带来的话，应该连带所有子进程都做同样设定

**Comment by eycorsican** [comment]
匹配文件路径似乎更好

**Comment by patrickwangqy** [comment]
路径的话像uwp的app就没有办法啦
________________________________

**Comment by eycorsican** [comment]
uwp 应用的进程树结构和目录树结构是怎样的？

**Comment by patrickwangqy** [comment]
这个我倒没有细究过，但是这个任务管理器确实可以区分出uwp的进程结构，然后mellow也确实能让uwp走代理
________________________________

**Comment by patrickwangqy** [comment]
我并没有搜到关于uwp进程这块的资料哎
