### ISSUE TITLE
关于开源

### ISSUE THREAD

**Issue by demoshang** [eycorsican/Mellow#23]
![image](https://user-images.githubusercontent.com/26966709/65303270-24d24d80-dbb0-11e9-8260-20da99d764d4.png)

对于 `core` 和 `route` 是否开源?

**Comment by strongbugman** [comment]
core应该就是v2ray-core

**Comment by eycorsican** [comment]
route 就是 /sbin/route，开源 core 需要时间整理代码

**Comment by demoshang** [comment]
> 开源 core 需要时间整理代码

请问有具体计划吗? 谢谢!
