### ISSUE TITLE
Questions about Mellow and go-tun2socks

### ISSUE THREAD

**Issue by wi1dcard** [eycorsican/Mellow#28]
Hi, mellow maintainers. I just found this awesome project several hours ago, and it totally surprised me by that your idea is exactly what I'm thinking. However, there are also some questions while I was exploring it:

1. Is there any connection (e.g., depends on) between Mellow and [go-tun2socks](https://github.com/eycorsican/go-tun2socks)?
2. If yes, I see that the [core](https://github.com/eycorsican/Mellow/blob/master/helper/darwin/core) file might be a customized build of go-tun2socks, and `./core -version` indicates that the tag and commit hash are `v1.16.2` and `e3b3599`. I can't find this commit in go-tun2socks repo. Is the core file open sourced?
3. The latest release of go-tun2socks seems removed the "native" support of V2Ray (Vmess) proxy. If there's no planning for making core file open-source, can I replace the core file with my build of the open-source go-tun2socks project?

Thank you!

**Comment by strongbugman** [comment]
The core file is v2ray project's v2ray-core

**Comment by wi1dcard** [comment]
> The core file is v2ray project's v2ray-core

It seems not:

```
$ ./core -h
Usage of ./core:
  -delayICMP int
    	Delay ICMP packets for a short period of time, in milliseconds (default 10)
  -disableDNSCache
    	Disable DNS cache
  -dnsFallback
    	Enable DNS fallback over TCP (overrides the UDP proxy handler).
  -fakeDns
    	Enable Fake DNS
  -fakeDnsCacheDir string
    	Cache directory used by Fake DNS
  -fakeDnsMaxIP string
    	Maximum fake IP used by Fake DNS (default "172.30.16.255")
  -fakeDnsMinIP string
    	Minimum fake IP used by Fake DNS (default "172.30.0.0")
  -loglevel string
    	Logging level. (debug, info, warn, error, none) (default "info")
  -proxyType string
    	Proxy handler type (default "socks")
  -relayICMP
    	Relay ICMP packets
  -rpcPort int
    	Management RPC port. (default 6002)
  -sendThrough string
    	Send through address. (default "192.168.0.100")
  -sniffingType string
    	Enable domain sniffing for specific kind of traffic in v2ray (default "http,tls")
  -stats
    	Enable statistics, open http://localhost:6001/stats/session/plain in your browser to view statistics
  -tunAddr string
    	TUN interface address (default "10.255.0.2")
  -tunDns string
    	DNS resolvers for TUN interface (only need on Windows) (default "223.5.5.5,1.1.1.1")
  -tunGw string
    	TUN interface gateway (default "10.255.0.1")
  -tunMask string
    	TUN interface netmask, it should be a prefixlen (a number) for IPv6 address (default "255.255.255.0")
  -tunName string
    	TUN interface name (default "tun1")
  -udpTimeout duration
    	UDP session timeout (default 1m0s)
  -vconfig string
    	Config file for v2ray, in JSON format, and note that routing in v2ray could not violate routes in the routing table (default "config.json")
  -version
    	Print version
```

**Comment by strongbugman** [comment]
oh you are right, my careless

**Comment by eycorsican** [comment]
1. The `core`  is built from a branch based on go-tun2socks.

2. Not yet open-source.

3. I'm afraid simply replace the core with go-tun2socks won't work.

**Comment by wi1dcard** [comment]
Thanks!
