### ISSUE TITLE
如何实现lan共享？

### ISSUE THREAD

**Issue by poemsiu** [eycorsican/Mellow#32]
如题，能否实现局域网内共享代理？在配置文件写了inbound配置监听0.0.0.0:10808报错无法connect。

**Comment by eycorsican** [comment]
s什么系统？防火墙关了没？

**Comment by poemsiu** [comment]
@eycorsican 系统win10 和防火墙有关吗 用v2rayN是没问题的

**Comment by eycorsican** [comment]
测试过没问题。
