### ISSUE TITLE
DNS中使用localhost导致DNS失效

### ISSUE THREAD

**Issue by ZZYSonny** [eycorsican/mellow#33]
猜测原因可能是mellow启动后，系统默认DNS变成了mellow的，导致这个DNS查询由mellow发出，mellow接受，无限循环。
可以考虑在启动前把localhost替换为本地DNS。

localhost在需要使用本地DNS，并且需要连接不同网络（本地DNS不同时）会相当有用。

下面是https://www.v2ray.com/chapter_02/04_dns.html 中关于localhost的解释
> 当值为"localhost"时，表示使用本机预设的 DNS 配置。
当使用 localhost 时，本机的 DNS 请求不受 V2Ray 控制，需要额外的配置才可以使 DNS 请求由 V2Ray 转发。

**Comment by eycorsican** [comment]
s涉及到系统DNS、localhost 时要指明对应操作系统，windows跟其它系统的底层处理有很大区别

**Comment by ZZYSonny** [comment]
我用的是Windows。
试了一下把localhost替换成本地DNS是可行的

**Comment by eycorsican** [comment]
你同时也配置了 DNS 分流吧？这样配置在 Windows 上的确会造成死循环

**Comment by ZZYSonny** [comment]
的确配置了dns分流
能否考虑在启动前把localhost自动替换为当前的dns?
