### ISSUE TITLE
macOS不稳定的issue

### ISSUE THREAD

**Issue by rsun-thoughtworks** [eycorsican/mellow#36]
MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Catalina Version 10.15

1. connect 点击后，不一定有效，反复disconnect和connect后，偶尔可以正常工作
2. 偶现和微信mac版不能共同工作的问题，一打开微信，Mellow就报错。

**Comment by eycorsican** [comment]
报什么错？日志？

**Comment by rsun-thoughtworks** [comment]
> 报什么错？日志？

下次重现的时候，会提供详细的log

**Comment by 0njzy0** [comment]
不能正常工作就是因为在网络发生变化是比如wifi切换，路由表不能正常设置引起的。

**Comment by greatbody** [comment]
先关掉这个issue把，啥时候重现了再看。

**Comment by eycorsican** [comment]
issue 我就先关了，我日常也用 macOS，没任何问题

**Comment by GavinZLiang** [comment]
如果显示打开Core失败以及找不到Tun该怎么办
