### ISSUE TITLE
IPV4环境下，能否去除dns_out请求AAAA的操作？

### ISSUE THREAD

**Issue by betterdoitnow** [eycorsican/Mellow#37]
主要是请求AAAA浪费时间和资源，有的域名没有返回AAAA的话，还要等超时。能否做个开关选项？

**Comment by eycorsican** [comment]
https://support.opendns.com/hc/en-us/articles/227988887-How-to-Disable-IPv6

**Comment by betterdoitnow** [comment]
谢谢！
