### ISSUE TITLE
outbound support http

### ISSUE THREAD

**Issue by 0njzy0** [eycorsican/mellow#41]
like this [pr](https://github.com/v2ray/v2ray-core/pull/1813)

**Comment by eycorsican** [comment]
Why should we support HTTP endpoint?

**Comment by 0njzy0** [comment]
> Why should we support HTTP endpoint?

Use with the [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic/issues/267)

**Comment by 0njzy0** [comment]
At this stage, there is really no need to support it. I can cooperate with other software implementations and shut down first.

**Comment by eycorsican** [comment]
@0njzy0 master 上支持了

**Comment by 0njzy0** [comment]
Test it, no problem, leave the configuration

```json
{
  "log": {
    "loglevel": "debug"
  },
  "outbounds": [
    {
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 1080
          }
        ]
      }
    },
    {
      "protocol": "http",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 8831
          }
        ]
      },
      "tag": "unblockneteasemusic"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "domain": [
          "music.163.com",
          "music.126.net"
        ],
        "app": [
          "NeteaseMusic",
          "com.apple.WebKit.Networking"
        ],
        "type": "field",
        "outboundTag": "unblockneteasemusic"
      },
      {
        "app": [
          "*shadowsocks*",
          "ShadowsocksX-NG",
          "ClashX",
          "clash"
        ],
        "type": "field",
        "outboundTag": "direct"
      }
    ]
  }
}
```

**Comment by eycorsican** [comment]
I would recommend using the more compact `conf` format config file:
```ini
[Endpoint]
direct, builtin, freedom, domainStrategy=UseIP
unblock_netease, builtin, http, address=127.0.0.1, port=10027

[RoutingRule]
PROCESS-NAME, node, direct
PROCESS-NAME, NeteaseMusic, unblock_netease
DOMAIN-SUFFIX, music.163.com, unblock_neteas
FINAL, direct
```

Then you just run `UnblockNeteaseMusic` locally, and you are good to go:
```sh
cd UnblockNeteaseMusic
node app.js -p 10027
```

Since we are running UnblockNeteaseMusic locally, there is no need to worry about certificate issues.

p.s. UnblockNeteaseMusic is a great project :)

**Comment by laggardkernel** [comment]
@eycorsican Can we create `[Endpoint]` in Kitsunebi Android now?  UnblockNeteaseMusic could also be run on Android, but I don't find a way to use the http outbound in Kitsunebi Anroid.

**Comment by eycorsican** [comment]
@laggardkernel HTTP oubound was supported in custom config in the latest Kitsunebi Android release.

**Comment by laggardkernel** [comment]
你现在怎么部署 UnblockNeteaseMusic？我如果部署在本地且使用 HTTPS 连接。开启 Mellow 后 HTTPS 连接建立不起来。

```shell
/usr/local/bin/node /usr/local/deploy/UnblockNeteaseMusic/app.js -a 127.0.0.1 -p 16300:16301 -f 223.252.199.66 -e https://music.163.com -s
```

从终端的输出中可以看到，UnblockNetease接收到了请求，且 Mellow session 中也可见。Wireshark 可以看到向 `223.252.199.66` 地址发起的 TLS 握手，但貌似不成功，这个握手过程反复发起。

关闭 Mellow 后一起又正常了……
