### ISSUE TITLE
Linux 版本能否编译一个 ARM 架构的

### ISSUE THREAD

**Issue by ToutyRater** [eycorsican/mellow#43]
类树莓派的 SBC 都是 ARM 架构的，要是能有一个 ARM 架构版本的就更好了，那样可以直接运行在 SBC 上充当翻墙网关

**Comment by eycorsican** [comment]
我编译了一个，你测试一下？运行方式参考：https://github.com/eycorsican/mellow#%E5%8F%AF%E4%BB%A5%E5%9C%A8-linux-%E4%B8%8A%E4%BB%A5%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%96%B9%E5%BC%8F%E8%BF%90%E8%A1%8C%E5%90%97

https://github.com/eycorsican/mellow/releases/download/v0.1.4/core-linux-arm64

**Comment by poemsiu** [comment]
> 类树莓派的 SBC 都是 ARM 架构的，要是能有一个 ARM 架构版本的就更好了，那样可以直接运行在 SBC 上充当翻墙网关

老哥你试的怎么样？

**Comment by eycorsican** [comment]
@ToutyRater 你还可以试下在路由器上做透明代理：https://github.com/eycorsican/mellow#%E5%8F%AF%E4%BB%A5%E8%BF%90%E8%A1%8C%E5%9C%A8%E8%B7%AF%E7%94%B1%E5%99%A8%E4%B8%8A%E5%81%9A%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E5%90%97
