### ISSUE TITLE
真der!好用我滴天！

### ISSUE THREAD

**Issue by yoheRabit** [eycorsican/mellow#44]
用过v2rayU和v2rayX,但都不太好用，pac并不适合我，全局更加不方便。邮箱不能设置代理，所以我尝试下载了代理app的Proxifier，它是收费的，我下的破解版，但似乎和v2rayU发生了一些冲突，也有可能是我设置不当，反正很快就卸载了。我在手机上用的就是作者的Kitsunebi，在作者推特上看到了这个项目，出于Kitsunebi的良好使用体验，我尝试了mellow，尽管它并没有gui。
  果然它就是我需要的，简单上手，谢谢作者的努力，它是我目前找到的最优秀的v2ray mac端的代理App，分流很好，邮箱也工作了。加油！看好Mellow！

**Comment by yoheRabit** [comment]
我是最新Catalina，如果有和我一样环境的伙伴，强烈安利！

**Comment by eycorsican** [comment]
你舒服就好
