### ISSUE TITLE
WiFi切换另一个网络后，mellow需要reconnect

### ISSUE THREAD

**Issue by yoheRabit** [eycorsican/mellow#45]
如题，正常使用状态下，切换另一个网络连接，mellow不能随之切换，需要手动reconnect后才能使用。请问作者大大是不是现在的版本是不是还未实现切换？谢谢作者大大。

**Comment by 0njzy0** [comment]
确实需要一个网络状态监听的功能，之前试了electron文档的检测方法和route monitor方法，都无法准确获取网络状态。

**Comment by eycorsican** [comment]
修了个小 bug，目前是采用主动检测的方法，最多 60 秒会自动重新连接：https://github.com/eycorsican/mellow/blob/9d900919fdab1cafa902ebb62e04cb507a622064/src/main.js#L1130

**Comment by 0njzy0** [comment]
> 修了个小 bug，目前是采用主动检测的方法，最多 60 秒会自动重新连接：
> 
> https://github.com/eycorsican/mellow/blob/9d900919fdab1cafa902ebb62e04cb507a622064/src/main.js#L1130

大佬 有没有更精确的思路 比如事件监听之类的

**Comment by 0njzy0** [comment]
> > 修了个小 bug，目前是采用主动检测的方法，最多 60 秒会自动重新连接：
> > https://github.com/eycorsican/mellow/blob/9d900919fdab1cafa902ebb62e04cb507a622064/src/main.js#L1130
> 
> 大佬 有没有更精确的思路 比如事件监听之类的

还有就是目前这个60秒自动重连，不就是检测running吗，我wifi如果换成了别的，还是不起作用啊。
