### ISSUE TITLE
请教一下关于DNS的问题

### ISSUE THREAD

**Issue by cbdog94** [eycorsican/Mellow#5]
现在的问题应该是无法使用配置文件中的DNS进行域名解析
系统macOS 10.14.6
尝试过的一些操作
1. 将WiFi接口的DNS设为8.8.8.8是能正常工作的，在此之前是路由器IP，路由器的DNS大概是联通的
2. 将路由规则改成 "rules": [
            {
                "ip": [
                    "0.0.0.0/0",
                    "::/0"
                ],
                "type": "field",
                "outboundTag": "proxy"
            }
        ]
也就是所有流量都走代理，国内网站是能正常解析的，百度显示的IP也是代理的IP，但是国外网站（google...）解析不出来
所以猜测是DNS的问题，不知道是不是配置的不对
配置文件：
{
    "log": {
        "loglevel": "warning"
    },"dns": {
        "hosts": {
            "localhost": "127.0.0.1"
        },
        "servers": [
            {
                "address": "8.8.8.8",
                "port": 53
            },
            {
                "address": "223.5.5.5",
                "port": 53,
                "domains": [
                    "geosite:cn"
                ]
            }
        ]
    },
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "users": [
                            {
                                "id": "*****************",
                                "alterId": 2,
                                "security": "auto"
                            }
                        ],
                        "address": "**********",
                        "port": 443
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": null,
                "tcpSettings": null,
                "kcpSettings": null,
                "wsSettings": null,
                "httpSettings": null
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "direct"
            },
            {
                "ip": [
                    "0.0.0.0/0",
                    "::/0"
                ],
                "type": "field",
                "outboundTag": "proxy"
            }
        ]
    }
}

**Comment by eycorsican** [comment]
等会发布0.0.7应该能解决
