### ISSUE TITLE
mellow配合clash时，clash链接远端代理的ip请求被dispatcher解析为 混淆后的域名请求

### ISSUE THREAD

**Issue by Masstone** [eycorsican/mellow#52]
<img width="999" alt="截屏2019-10-20下午1 20 17" src="https://user-images.githubusercontent.com/1457421/67155267-30936a00-f33e-11e9-9454-7fc18c36b092.png">

clash里链接用的节点
<img width="287" alt="截屏2019-10-20下午1 44 06" src="https://user-images.githubusercontent.com/1457421/67155349-ce3b6900-f33f-11e9-8ffa-d077fc61e956.png">

@eycorsican 

我用了和 @0njzy0  一样的配置，但发现clash链接远端的请求被dispatcher解析为混淆的域名。导致连接失败。

clash直连的没问题

_Originally posted by @Masstone in https://github.com/eycorsican/mellow/issues/3#issuecomment-544222440_

**Comment by eycorsican** [comment]
你可以尝试下使用 hosts 功能去解决：https://v2ray.com/chapter_02/04_dns.html

```json
"hosts": {
    "xxx.windows.com": "vps.com"
}
```

**Comment by Masstone** [comment]
> 你可以尝试下使用 hosts 功能去解决：https://v2ray.com/chapter_02/04_dns.html
> 
> ```json
> "hosts": {
>     "xxx.windows.com": "vps.com"
> }
> ```

{
  "log": {
    "loglevel": "debug"
  },
  "outbounds": [
    {
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 7891
          }
        ]
      },
      "tag": "socks5"
    },
    {
      "protocol": "freedom",
      "domainStrategy": "UseIP",
      "tag": "direct"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "app": [
          "app.js",
          "*shadowsocks*",
          "ShadowsocksX-NG",
          "ClashX",
          "clash",
          "unknown process",
          "Surge 3"
        ],
        "type": "field",
        "outboundTag": "direct"
      }
    ]
  },
  "dns": {
      "hosts": {
        "1aba720679.wns.windows.com": "47.xxx.xxx.xxx"
      },
      "servers": [
        "119.29.29.29"
      ]
  }
}


我这样尝试了还是连不上

**Comment by Masstone** [comment]
哦 是我"domainStrategy": "UseIP",配错地方了。

不过这样还有个问题是，多个节点ip用同一个混淆域名，就不知道该咋办了

**Comment by eycorsican** [comment]
自己改代码关 sniffing。

**Comment by Masstone** [comment]
> 自己改代码关 sniffing。

刚刚试了关掉sniffing，结果所有入站的流量都经过了系统dns的解析，拿不到域名了

这个youtube视频的污染无法解决了

**Comment by eycorsican** [comment]
fakeDns

**Comment by Masstone** [comment]
> fakeDns

嗯  

  "dns": {
    "servers": [
      {
        "address": "127.0.0.1",
        "port": 53
      },
      "localhost"
    ]
  },



{
        "inboundTag": [
          "tun2socks"
        ],
        "network": "udp",
        "port": 53,
        "outboundTag": "dns_out",
        "type": "field"
      }


这个是吧，我才知道有一个默认的inbound是tun2socks

**Comment by eycorsican** [comment]
fakeDns 是命令行的一个选项，跟 sniffing 一样可以拿到请求的域名，因为原理不一样所以 fakeDns 不会受伪装域名的影响，缺点是会染污系统 DNS 缓存以及 ping 或 dig 某个域名的时候拿不到真正的 IP。

```
$ /Library/Application\ Support/Mellow/core -h
Usage of /Library/Application Support/Mellow/core:
  -delayICMP int
    	Delay ICMP packets for a short period of time, in milliseconds (default 10)
  -disableDNSCache
    	Disable DNS cache
  -dnsFallback
    	Enable DNS fallback over TCP (overrides the UDP proxy handler).
  -fakeDns
    	Enable Fake DNS

...
```

**Comment by Masstone** [comment]
> fakeDns 是命令行的一个选项，跟 sniffing 一样可以拿到请求的域名，因为原理不一样所以 fakeDns 不会受伪装域名的影响，缺点是会染污系统 DNS 缓存以及 ping 或 dig 某个域名的时候拿不到真正的 IP。
> 
> ```
> $ /Library/Application\ Support/Mellow/core -h
> Usage of /Library/Application Support/Mellow/core:
>   -delayICMP int
>     	Delay ICMP packets for a short period of time, in milliseconds (default 10)
>   -disableDNSCache
>     	Disable DNS cache
>   -dnsFallback
>     	Enable DNS fallback over TCP (overrides the UDP proxy handler).
>   -fakeDns
>     	Enable Fake DNS
> 
> ...
> ```

所以用这个的话就不需要自己写配置给dns请求分流了？

**Comment by laggardkernel** [comment]
> 刚刚试了关掉sniffing，结果所有入站的流量都经过了系统dns的解析，拿不到域名了
>
> 这个youtube视频的污染无法解决了

@eycorsican 我现在是在Mellow使用SSR客户端的本地Socks代理，好像我关了 domain sniffing 才能正常使用。但没开 fakedns DNS依然可以解析正常。上面的问题是修复了？

**Comment by zhangxu3486432** [comment]
请问您是怎么在 clash 配置文件里面关闭 sniffing 的呀？

我试了两种方式均无效：

```yaml
sniffing: false
```

```yaml
sniffing: 
    enable: false
```
