### ISSUE TITLE
能支持中文吗？安装了一下，一脸懵逼

### ISSUE THREAD

**Issue by lxitdn** [eycorsican/Mellow#9]
能支持中文吗？安装了一下，一脸懵逼

**Comment by lunksana** [comment]
界面已经够简单了，还需要中文吗？

**Comment by lxitdn** [comment]
关键是不会配置，哈哈，如果有界面配置就好了

**Comment by w12559** [comment]
不会配置才是重点。。我模仿了下v2里面的东西填进去，貌似要出错

**Comment by patrickwangqy** [comment]
它不是有默认配置吗。只把outbound改一下就好了

**Comment by ntgeralt** [comment]
我觉得这产品缺少的是一个能用的json示范例程。起码有个格式可以给用户参考。例如纯tcp怎么填，4个ws tls节点怎么填。

反正我添加了几个节点，无法生效使用。看日志也一脸懵逼。

**Comment by ntgeralt** [comment]
我觉得这产品缺少的是一个能用的json示范例程。

反正我添加了几个节点，无法生效使用。看日志也一脸懵逼。想找个例程改一下也找不到。

**Comment by lunksana** [comment]
请结合kitsunebi-android的示例然后参照ReadMe中最下方的配置示例进行配置
